### ISSUE TITLE
Publish 0.5.0 with release notes

### ISSUE THREAD

**Issue by chriskrycho** [oli-obk/rust-pandoc#14]
Since you're likely to be pushing a new version up soon (!) it struck me that having a `CHANGELOG.md` is handy. I'm happy to write it up sometime today.

**Comment by oli-obk** [comment]
I'm not a fan of `CHANGELOG.md`, but github releases (https://github.com/oli-obk/rust-pandoc/releases) are a good idea.

**Comment by chriskrycho** [comment]
Seems reasonable to me!

I’m happy to draft that as well; I can… write up a draft here or something and you can pull it in?

**Comment by oli-obk** [comment]
sure

**Comment by chriskrycho** [comment]
Release notes for the 0.5.0 release! Rendered:

0.5.0 Changes

## Overview

Update the `Pandoc` interface to support several new configuration options, to support the use of the builder pattern, and to support returning the result of a Pandoc operation directly rather than always writing it to a file.

## Details

### Breaking changes

- update all builder-type methods on `Pandoc` to work as 
- support returning a string directly from Pandoc's `stdout`. Previously, all output was written to file. The output location must be set using the [`OutputKind`][OutputKind] type passed as an argument to [`Pandoc::set_output`][set_output]. All configurations now return the new [`PandocOutput`][PandocOutput] type.

[set_output]: https://docs.rs/pandoc/0.5.0/pandoc/struct.Pandoc.html#method.set_output
[OutputKind]: https://docs.rs/pandoc/0.5.0/pandoc/enum.OutputKind.html
[PandocOutput]: https://docs.rs/pandoc/0.5.0/pandoc/enum.PandocOutput.html

### Other changes

- add a [`Pandoc::show_cmd_line()`][show_cmd_line] method, which prints the generated command line call to `stdout` when it is run
- add a [`Pandoc::add_options()`][add_options] method, which works just like the existing `Pandoc::add_option()` method, but accepting a slice of [`PandocOption`][PandocOption] items rather than just one `PandocOption`


[show_cmd_line]: https://docs.rs/pandoc/0.5.0/pandoc/struct.Pandoc.html#method.show_cmd_line
[add_options]: https://docs.rs/pandoc/0.5.0/pandoc/struct.Pandoc.html#method.add_options
[PandocOption]: https://docs.rs/pandoc/0.5.0/pandoc/enum.PandocOption.html

### Under the hood

- update to use the JSON exchange format introduced in [Pandoc 1.18][1.18] and added support for a smattering of other features from 1.18 and [1.17][1.17]

[1.17]: http://pandoc.org/releases.html#pandoc-1.17-20-mar-2016
[1.18]: http://pandoc.org/releases.html#pandoc-1.18-26-oct-2016

---

Source:

```markdown
0.5.0 Changes

## Overview

Update the `Pandoc` interface to support several new configuration options, to support the use of the builder pattern, and to support returning the result of a Pandoc operation directly rather than always writing it to a file.

## Details

### Breaking changes

- update all builder-type methods on `Pandoc` to work as 
- support returning a string directly from Pandoc's `stdout`. Previously, all output was written to file. The output location must be set using the [`OutputKind`][OutputKind] type passed as an argument to [`Pandoc::set_output`][set_output]. All configurations now return the new [`PandocOutput`][PandocOutput] type.

[set_output]: https://docs.rs/pandoc/0.5.0/pandoc/struct.Pandoc.html#method.set_output
[OutputKind]: https://docs.rs/pandoc/0.5.0/pandoc/enum.OutputKind.html
[PandocOutput]: https://docs.rs/pandoc/0.5.0/pandoc/enum.PandocOutput.html

### Other changes

- add a [`Pandoc::show_cmd_line()`][show_cmd_line] method, which prints the generated command line call to `stdout` when it is run
- add a [`Pandoc::add_options()`][add_options] method, which works just like the existing `Pandoc::add_option()` method, but accepting a slice of [`PandocOption`][PandocOption] items rather than just one `PandocOption`


[show_cmd_line]: https://docs.rs/pandoc/0.5.0/pandoc/struct.Pandoc.html#method.show_cmd_line
[add_options]: https://docs.rs/pandoc/0.5.0/pandoc/struct.Pandoc.html#method.add_options
[PandocOption]: https://docs.rs/pandoc/0.5.0/pandoc/enum.PandocOption.html

### Under the hood

- update to use the JSON exchange format introduced in [Pandoc 1.18][1.18] and added support for a smattering of other features from 1.18 and [1.17][1.17]

[1.17]: http://pandoc.org/releases.html#pandoc-1.17-20-mar-2016
[1.18]: http://pandoc.org/releases.html#pandoc-1.18-26-oct-2016
```

**Comment by chriskrycho** [comment]
Note that the links above assume the release location for docs. Though there will be a slight delay, that should be fine by the time most people see the release notes.

**Comment by oli-obk** [comment]
Cool thanks! Copying it over noww

**Comment by chriskrycho** [comment]
👍 One more request… can you publish to crates.io? Thanks again!

**Comment by oli-obk** [comment]
done
