### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by kinnison** [oli-obk/rust-pandoc#28]
Last month I submitted a number of PRs around updates myself and a friend were making for our use of this crate.  We've settled and don't think we need more changes for now, so I'd like to formally request a new release of the `pandoc` crate.  I'm happy to prepare a PR for updating the version numbers etc, though I don't believe it's necessarily sensible to grant me the right to upload to crates.io for it.

If you want me to co-maintain the crate then I'm prepared to, though I'd expect to be pretty hands-off unless I need further changes to support my use-cases.

Just tell me how you'd like me to help, if you don't want to do the release entirely yourself, and I'll do my best.

Thanks,

D.

**Comment by oli-obk** [comment]
I'd be happy to give you co-access. There's no requirement or pressure to do anything fast or at all.

**Comment by kinnison** [comment]
OK, if you're good with that then let's go for it.

**Comment by kinnison** [comment]
I've accepted the invite on crates.io.  I'll try and prep a release PR next

**Comment by kinnison** [comment]
0.8.0 published.  docs.rs has it enqueued.  I'll close this once i've verified docs built ok

**Comment by kinnison** [comment]
All looks good, thanks Oli!
