### ISSUE TITLE
Do not hard-code paths to executables

### ISSUE THREAD

**Issue by matthiasbeyer** [oli-obk/rust-pandoc#3]
I'm myself on NixOS Linux and `/usr/bin`, `/usr/local` and so on do not exist there.

Please consider making this more flexible.

**Comment by oli-obk** [comment]
These are just hints. You can always configure your own through the `add_latex_path_hint` method.

**Comment by oli-obk** [comment]
Feel free to open another issue if the hints cause trouble on NixOS
