### ISSUE TITLE
Piped PDF output?

### ISSUE THREAD

**Issue by dkasak** [oli-obk/rust-pandoc#32]
Currently there's no `OutputFormat` for PDF. I realize that this is probably designed this way due to the way pandoc itself handles PDF output. However, because of this, I don't currently see a way of getting PDF output to a pipe. 

Is it possible? In Pandoc it is, because you can force output to stdout by passing `-o -`, but then I have no way of telling rust-pandoc that I want PDF output because there is no extension.

**Comment by oli-obk** [comment]
Ah, that's indeed a failure just of the wrapper itself. I'm not sure how to add this in a good way API wise, but we should add it
