### ISSUE TITLE
Publish latest commits to crates.io

### ISSUE THREAD

**Issue by jacob-pro** [oli-obk/rust-pandoc#40]
I am really grateful for the PR which added [the citeproc option](https://github.com/oli-obk/rust-pandoc/pull/39).
I'm currently using it via the `git=` option in my Cargo file, but I'm not able to publish my crate if [the dependency isn't published. 
](https://github.com/rust-lang/cargo/issues/6738)

Please can you bump the number and republish to crates.io?

**Comment by oli-obk** [comment]
published!

**Comment by jacob-pro** [comment]
thank you!
