### ISSUE TITLE
Add functions to allow input and output via stdin/stdout

### ISSUE THREAD

**Issue by humenda** [oli-obk/rust-pandoc#5]
The builder currently lacks functions to supply a string (via stdin) to Pandoc and read the result into a string (via stdout). It would be great, if this functionality could be added, since the Pandoc executable supports this and it would enable conversions on-the-fly.

Thanks

**Comment by chriskrycho** [comment]
@humenda note that I've created a PR to do this for the output side [here](https://github.com/oli-obk/rust-pandoc/pull/7), and expect to follow that up for the input side (probably next weekend). I'd welcome your thoughts on that interface.

**Comment by humenda** [comment]
This works like a charm, just tested in a sample project. The code looks fine
to me too. I would like to see this merged.

**Comment by oli-obk** [comment]
has been merged. Keeping this issue open for the input-part.
