### ISSUE TITLE
How to set MarkdownExtension?

### ISSUE THREAD

**Issue by flosse** [oli-obk/rust-pandoc#56]
I want to add the argument `-f markdown-implicit_figures` and [I found it](https://docs.rs/pandoc/latest/pandoc/enum.MarkdownExtension.html#variant.ImplicitFigures) but I don't know how to apply this :thinking:

**Comment by oli-obk** [comment]
I haven't used this crate in years. I don't know how to do what you are looking for either, but feel free to add support for it. I'll merge it and publish an update

**Comment by oli-obk** [comment]
Maybe https://docs.rs/pandoc/latest/pandoc/struct.Pandoc.html#method.set_input_format is what you are looking for?

**Comment by flosse** [comment]
> Maybe https://docs.rs/pandoc/latest/pandoc/struct.Pandoc.html#method.set_input_format is what you are looking for?

@oli-obk Thank you :pray:  That's exactly what I was looking for :relaxed:
